### ISSUE TITLE
Profile customize cell's affection ratio by full/delta traffic data

### ISSUE THREAD

**Issue by wangyoucao577** [Telenav/osrm-backend#49] opened 2019-07-30 23:18 UTC
- [Why this task](https://github.com/Telenav/osrm-backend/issues/49#issuecomment-520614813)
- [Design doc](https://github.com/Telenav/osrm-backend/issues/49#issuecomment-534803683)
- [Profile result](https://github.com/Telenav/osrm-backend/issues/49#issuecomment-547631416)

**Comment by CodeBear801** [comment] 2019-08-12 22:12
This task is part of #30, for more background please go to: https://github.com/Project-OSRM/osrm-backend/issues/5503

We noticed that OSRM will customize all cells during each round of customization, it tasks 10% of total time to load updated speed data, 30% to re-load OSRM data, 60% to do customization.  

We want to know if with partial traffic + only customize cells with updated traffic, whether the time cost could dramatically dropped.

**Comment by CodeBear801** [comment] 2019-08-14 23:58
For current OSRM's logic, in cell_customizer.hpp it will customize all cells from level 1 to level 4
```C++
    template <typename GraphT>
    void Customize(const GraphT &graph,
                   const partitioner::CellStorage &cells,
                   const std::vector<bool> &allowed_nodes,
                   CellMetric &metric) const
    {
        Heap heap_exemplar(graph.GetNumberOfNodes());
        HeapPtr heaps(heap_exemplar);

        for (std::size_t level = 1; level < partition.GetNumberOfLevels(); ++level)
        {
            tbb::parallel_for(tbb::blocked_range<std::size_t>(0, partition.GetNumberOfCells(level)),
                              [&](const tbb::blocked_range<std::size_t> &range) {
                                  auto &heap = heaps.local();
                                  for (auto id = range.begin(), end = range.end(); id != end; ++id)
                                  {
                                      Customize(
                                          graph, heap, cells, allowed_nodes, metric, level, id);
                                  }
                              });
        }
    }

```
Our idea is, when apply live traffic to each node, recording the cell id touched by him.  
In updater.cpp

```C++
if (auto value = segment_speed_lookup({u, v}))
{
	// update set<cellId> covered by u & v
	// for each node, need to find all upper level celles
}


if (auto value = segment_speed_lookup({v, u}))
{
	// update set<cellId> covered by v & u
	// for each node, need to find all upper level celles
}

```

Class MultiLevelPartitionImpl(view) provide ability to get CellID by given node and level.
```C++
    // returns the index of the cell the vertex is contained at level l
    CellID GetCell(LevelID l, NodeID node) const

```

The set will be transferred to Customize, during iteration, when cellid not in the set directly skip.  
The main point is output statistic of delta change ratio.

```C++
class CellFilter
{
	void Initialize();

	void Clear();

	// if cell need to be filtered
	// return true means cell hasn't be touched
	// return false means cell has been update, no need touch
	bool Filter(CellID id);

	// update all cells cover given node
	void Update(NodeId s);
}

```

**Comment by CodeBear801** [comment] 2019-08-29 16:42
For how customization works, please refer to here: 
https://github.com/Telenav/osrm-backend/issues/55#issuecomment-525062173

**Comment by CodeBear801** [comment] 2019-08-30 01:52
Several notes about the profile:

## Requirements
- The profile should not affect original logic.  Means it should be configurable, by default should be the same as old logic(customize all cells)
- The change should be testable

## Notes
- About where to add class CustomizerCellFilter, now I am thinking in CellCustomizer
  There should be a factory to create different CustomizerCellFilters, by default Filter will always return false
- During code debugging, I pay more attention to the parameter of 'allowed_nodes' for function call [Customize()](https://github.com/Telenav/osrm-backend/blob/9c43ff531bfbcb93e860f448f915ec529067ce9a/include/customizer/cell_customizer.hpp#L116).
  - allowed_nodes is used for "avoid_toll" or "avoid_highway".
  - The vector of allowed_nodes matches each nodeid
  - There could be several allowed_nodes vector and will generate different metrics
  - For each node, the value of allowed_nodes set to false means such node is excluded from graph.  During route calculation will skip such node, and if such node is the boundary node of the cell, during customization will assign "INVALID_EDGE_WEIGHT" to the in&out value
  - classes has been set during lua import, for 'toll', 'motorway', 'ferry', 'restricted', 'tunnel'
API of Customize()
```C++
    template <typename GraphT>
    void Customize(const GraphT &graph,
                   const partitioner::CellStorage &cells,
                   const std::vector<bool> &allowed_nodes,
                   CellMetric &metric) const
```
Customize for different metrics
```C++
std::vector<CellMetric> customizeFilteredMetrics(const partitioner::MultiLevelEdgeBasedGraph &graph,
                                                 const partitioner::CellStorage &storage,
                                                 const CellCustomizer &customizer,
                                                 const std::vector<std::vector<bool>> &node_filters)
{
    std::vector<CellMetric> metrics;

    for (auto filter : node_filters)
    {
        auto metric = storage.MakeMetric();
        customizer.Customize(graph, storage, filter, metric);
        metrics.push_back(std::move(metric));
    }

    return metrics;
}
```
How node_filter is constructed
```C++
inline std::vector<std::vector<bool>>
excludeFlagsToNodeFilter(const NodeID number_of_nodes,
                         const extractor::EdgeBasedNodeDataContainer &node_data,
                         const extractor::ProfileProperties &properties)
{
    std::vector<std::vector<bool>> filters;
    for (auto mask : properties.excludable_classes)
    {
        if (mask != extractor::INAVLID_CLASS_DATA)
        {
            std::vector<bool> allowed_nodes(number_of_nodes);
            for (const auto node : util::irange<NodeID>(0, number_of_nodes))
            {
                allowed_nodes[node] = (node_data.GetClassData(node) & mask) == 0;
            }
            filters.push_back(std::move(allowed_nodes));
        }
    }
    return filters;
}
```

- For unit test, I think cell_customization.cpp gives me a good example.
  First I will write a file to test customization when speed value changes.
  Then when the filter is enabled, the customization result is still correct.

**Comment by CodeBear801** [comment] 2019-09-11 21:56
Back to real world. :):)

## Current logic
- In customizer.cpp, it will call `LoadAndUpdateEdgeExpandedGraph` to load data from csv and update edge expand graph
Then will call `customizeFilteredMetrics` to update **all** metrics' cost

- Inside `LoadAndUpdateEdgeExpandedGraph`, it will call `updateSegmentData` and `updateTurnPenalties` in updater.cpp to update cost for segment and tuns

- Please note that `LoadAndUpdateEdgeExpandedGraph` will also be called by contractor

## Potential change
- During `customizeFilteredMetrics`, avoid customize the cells hasn't been touched
-  Use `CustomizerCellFilter` to record which cell has cost change
- In `LoadAndUpdateEdgeExpandedGraph`, record all nodes been touched, using set or unordered_set
- In customizer.cpp, based on the nodes been touched, generated cells coverred such nodes
- In  `CustomizerCellFilter`, avoid touching related cells

**Comment by CodeBear801** [comment] 2019-09-25 00:51
# Main changes
- During `parseArguments` in customize.cpp, add new boolean flag of `incremental` to indicate whether rebuild cost metrix or incrementally build metrix.  By default its false means the same as original version.
- During `Customizer::Run`, if config.updater_config.incremental is false, same as before.  `util::ConcurrentSet<NodeID> node_updated` will not collect any updated node ids, and `CellUpdateRecord cell_update_record` will always return true for `Check()` which means all cells need to be Customized. 
- During `Customizer::Run`, if config.updater_config.incremental is true, will load `cell_metrics` from file and only change the part need to be updated.  `util::ConcurrentSet<NodeID> node_updated` will collect all nodes which have speed update, then `CellUpdateRecord cell_update_record` will collect all cell ids covered those nodes, during Customization, when iterating all cells, we only recaculate cost for cells inside cell_update_record
- Finally will persistent metrix into files 

# Testing
- unit test for ConcurrentSet
- unit test for CellUpdateRecord
- test for the flag of incremental
- generate sample speed.csv, verify cell customization as expected, only affect cell has been updated, final metrix has been recorded.

# Old logic
https://github.com/Telenav/open-source-spec/blob/master/osrm/references/pictures/osrm_customization_old.png

# New logic
https://github.com/Telenav/open-source-spec/blob/master/osrm/references/pictures/osrm_customization_new.png

**Comment by CodeBear801** [comment] 2019-09-28 00:17
During 09/27/2019's testing, I met a core dump in docker, cannot reproduce which on osx.
```
Segmentation fault (core dumped)
```
Testing description
Using osrm-professional-na's data + tomtom traffic.
step 1: generate full metric
step 2: get partial traffic data and using incremental mode to generate new metric.

**Comment by CodeBear801** [comment] 2019-09-28 00:48
I use entire day to debug and trace code for root cause, finally add one line of code and I am pretty happy I got more deep understanding for extraction and partition.

## Root cause
During node collection, we will collect inner nodes which don't have CellID, and during the function call of GetCell it crashed.
```C++
    CellID GetCell(LevelID l, NodeID node) const
    {
        auto p = partition[node];
        auto lidx = LevelIDToIndex(l);
        auto masked = p & level_data->lidx_to_mask[lidx];
        return masked >> level_data->lidx_to_offset[lidx];
    }
    
    Vector<PartitionID> partition;
```
The parameter passing into is (1, 4561984) while the array of partition only has 4288115 elements.  Add following code is needed protection
```C++
    CellID GetCell(LevelID l, NodeID node) const
    {
        if (node > partition.size() || l > GetNumberOfLevels()) 
            return INVALID_CELL_ID;
```
But to make sure we don't have bugs in other places I have a reading and debugging on OSRM's code.

Question 1: whether all nodes have cellid?
No.  For example, based on the sample data testing
```
[info] Loaded compressed node based graph: 4490432 edges, 16637952 nodes
```
While for the array of partition there are only 4288115 cells.

Question 2: Why So?  
## OSRM::Partition
Partition mainly depend on the following 3 files as input
```C++
    if (!check_file(partition_config.GetPath(".osrm.ebg")) ||
        !check_file(partition_config.GetPath(".osrm.cnbg_to_ebg")) ||
        !check_file(partition_config.GetPath(".osrm.cnbg")))
```
What are they?

## OSRM::Extractor
The entrance is 
```C++
int Extractor::run(ScriptingEnvironment &scripting_environment)
```
### Step 1
First construct node based graph
```C++
    NodeBasedGraphFactory node_based_graph_factory(config.GetPath(".osrm"),
                                                   scripting_environment,
                                                   turn_restrictions,
                                                   conditional_turn_restrictions,
                                                   unresolved_maneuver_overrides);
```
The most important step inside is [compress](https://github.com/Telenav/osrm-backend/blob/951af0c245da0155363535415a6d73cb225d5864/src/extractor/graph_compressor.cpp#L34), which combine degree 2 vertices, delete data from original graph and combine data into start node.
```C++
void GraphCompressor::Compress()
```
In the end of this step it will generate NodeBasedDynamicGraph.
```C++
using NodeBasedDynamicGraph = DynamicGraph<NodeBasedEdgeData>;
```
DynamicGraph is the graph contains node/edge information, plus it support add/delete operation, that's why its name is Dynamic.
```C++
template <typename EdgeDataT> class DynamicGraph
{
    NodeIterator number_of_nodes;
    std::atomic_uint number_of_edges;

    std::vector<Node> node_array;
    DeallocatingVector<Edge> edge_list;

    EdgeRange GetAdjacentEdgeRange(const NodeIterator node) const
    {
        return irange(BeginEdges(node), EndEdges(node));
    }
```
Final result dump into file of cnbg
```C++
    files::writeCompressedNodeBasedGraph(config.GetPath(".osrm.cnbg").string(),
                                         toEdgeList(node_based_graph));

EdgeList is {}
struct CompressedNodeBasedGraphEdge
{
    NodeID source;
    NodeID target;
};
```
In my sample data, it shows there are high node and edge compression ratio, which means lots of nodes are combined and edges has been deleted.
```
[info] Node compression ratio: 0.161598
[info] Edge compression ratio: 0.205774
```

### Step 2
`EdgeID Extractor::BuildEdgeExpandedGraph` calls `void EdgeBasedGraphFactory::Run`

#### Step 2.1
Generate nodes based graph mapping, the final result will sort node id and only record the one "end node id " > "from node id".  Final result has been wrote to cnbg.
```
files::writeNBGMapping(cnbg_ebg_mapping_path, mapping);

struct NBGToEBG
{
    NodeID u, v;
    NodeID forward_ebg_node, backward_ebg_node;
};

```

#### Step 2.2
`void EdgeBasedGraphFactory::GenerateEdgeExpandedEdges`

**Comment by wangyoucao577** [comment] 2019-09-30 02:27
Two graphs, FYI: 
- [osrm-extract Startup and Process Call Graph](https://github.com/Telenav/open-source-spec/blob/master/osrm/graph/osrm-extract_startup_and_process_callgraph.mmd.png)
- [osrm-customize Startup and Process Call Graph](https://github.com/Telenav/open-source-spec/blob/master/osrm/graph/osrm-customize_startup_and_process_callgraph.mmd.png)

**Comment by wangyoucao577** [comment] 2019-09-30 02:29
Still have questions: 
1. why not all `edges/nodes` in `cells`? 
2. what's the `compression ratio` mean? `remain / all` or `(all - remain) / all` ?

**Comment by CodeBear801** [comment] 2019-09-30 17:27
> Still have questions:
> 
> 1. why not all `edges/nodes` in `cells`?
I think you mean, during collection, why not only collect nodes/edges in `cell`. 
If so, I think it depends on where we want to handle this part of logic:
The input contains all edges which contains traffic update
During customization, it will update original graph for the cost/travel time part, along with this part of logic I implement the code of collecting changed node id.  This part I just want to collect raw node id be changed which has similar purpose with context.
Then I will iterate all nodes in the set and try to find cell id for them, I want to handle logic in this part: node id which in the final cell will be collect cell id, while node id already be combined will return invalid_cell_id
In the last step, during customization, I will check whether cell id has node be updated, if so, then will customize which, otherwise will skip customization.

> 2. what's the `compression ratio` mean? `(remain / all) * 100` or `((all - remain) / all) * 100` ?

`compression ratio` means remain/all.  Most of original edges from OSM data will be combined.

**Comment by CodeBear801** [comment] 2019-09-30 17:35
> Two graphs, FYI:
> 
> * [osrm-extract Startup and Process Call Graph](https://github.com/Telenav/open-source-spec/blob/master/osrm/graph/osrm-extract_startup_and_process_callgraph.mmd.png)
> * [osrm-customize Startup and Process Call Graph](https://github.com/Telenav/open-source-spec/blob/master/osrm/graph/osrm-customize_startup_and_process_callgraph.mmd.png)

Thanks for the graph.  Another thing I think is very important is why create those data structures.
https://github.com/Project-OSRM/osrm-backend/wiki/Toolchain-file-overview
https://github.com/Project-OSRM/osrm-backend/wiki/Processing-Flow

Those two wiki also helps, but need additional effort to map with existing code.

**Comment by wangyoucao577** [comment] 2019-10-08 02:16
> > Still have questions:
> > 
> > 1. why not all `edges/nodes` in `cells`?
> 
> I think your question is, during collection, why not only collect nodes/edges in `cell`.
> If it is, I think it depends on where we want to handle this part of logic:
> 
> * The input contains all edges which contains traffic update
> * At beginning of customization, it will update original graph for the cost/travel time part, all nodes and edges no matter its combined or not will be updated if there is speed update in the input file.  Along with this part of logic I implement the code of **collecting changed node ids**.  This part I just want to collect raw node id be changed which has similar purpose with context.  There is no concept of cell/mlp in this part.
> * Then I will iterate all nodes in the set and try to find cell id for them, node id which in the cell will collect cell id, while node id already be combined will return invalid_cell_id because there is no cell id for them
> * In the last step, during customization, I will check whether cell id exists in the upper step, if so which means there are node be updated inside and its cost need to be updated thus need customize function, otherwise will skip customization for the cell.

No, my question is why the `nodeid` can be bigger than cell's length in 
```c++
    CellID GetCell(LevelID l, NodeID node) const
    {
        if (node > partition.size() || l > GetNumberOfLevels()) 
            return INVALID_CELL_ID;
```
Does this mean some `node` will not in cell? Are they abondanded? Or something else?

**Comment by CodeBear801** [comment] 2019-10-08 17:32
> > > Still have questions:
> > > 
> > > 1. why not all `edges/nodes` in `cells`?
> > 
> > 
> > I think your question is, during collection, why not only collect nodes/edges in `cell`.
> > If it is, I think it depends on where we want to handle this part of logic:
> > 
> > * The input contains all edges which contains traffic update
> > * At beginning of customization, it will update original graph for the cost/travel time part, all nodes and edges no matter its combined or not will be updated if there is speed update in the input file.  Along with this part of logic I implement the code of **collecting changed node ids**.  This part I just want to collect raw node id be changed which has similar purpose with context.  There is no concept of cell/mlp in this part.
> > * Then I will iterate all nodes in the set and try to find cell id for them, node id which in the cell will collect cell id, while node id already be combined will return invalid_cell_id because there is no cell id for them
> > * In the last step, during customization, I will check whether cell id exists in the upper step, if so which means there are node be updated inside and its cost need to be updated thus need customize function, otherwise will skip customization for the cell.
> 
> No, my question is why the `nodeid` can be bigger than cell's length in
> 
> ```c++
>     CellID GetCell(LevelID l, NodeID node) const
>     {
>         if (node > partition.size() || l > GetNumberOfLevels()) 
>             return INVALID_CELL_ID;
> ```
> 
> Does this mean some `node` will not in cell? Are they abondanded? Or something else?

Not all node from osm data have related cellid.  The comments there are explaining this.

**Comment by CodeBear801** [comment] 2019-10-29 21:11
## Profile result

If traffic update frequency is about 30 seconds, total nodes in the graph be updated is 0.1%, about 3%'s cell need to be customized
If traffic update frequency is about 120 seconds, total nodes in the graph be updated is 1%~2%, about 25%'s cell need to be customized
If traffic update frequency is about 30 seconds, total nodes in the graph be updated is 2.5%, about 35%~38%'s cell need to be customized

**Closed** 2019-10-29 21:22 UTC
Labels: Implementation
